#! /usr/bin/env ruby

require "rss"
require "fileutils"

class Rebuild
  def initialize
    @command = ARGV
    begin
      @rss = RSS::Parser.parse("http://feeds.rebuild.fm/rebuildfm")
    rescue SocketError
      puts "Can't connect Internet"
    end
    @home = Dir.home
  end

  def download
    create_directory
    @rss.items.each do |item|
      Dir.chdir(download_directory) do
	title = item.title.delete("/")
	next if File.exist?("#{title}.mp3")
	puts "Now download -> #{title}"
	system("curl",
	       "--location",
	       "--output",
	       "#{title}.mp3",
	       "#{item.enclosure.url}")
      end
    end
  end

  private
  def download_directory
    File.join(@home, "rebuild")
  end

  def ep_directory
    File.join(@home, "rebuild", "ep")
  end

  def aftershow_directory
    File.join(@home, "rebuild", "aftershow")
  end
  
  def create_directory
    FileUtils.mkdir_p(download_directory) unless Dir.exist?(download_directory)
  end
end

rebuild = Rebuild.new
rebuild.download
